name: Cmake build and test on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.6.0
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          git fetch --all --tags -f

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: ${{ runner.temp }}

      - name: Configure Cmake
        run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=0

      - name: Build
        run: |
          cd build
          cmake --build build -j4

      - name: Test
        run: ctest

      - name: Collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"