name: Style Checker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C++ Style
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v3
      - name: Run style checks
        uses: coleaeason/actions-uncrustify@v1
        with:
          configPath: 'default.cfg'